version: "3"
services:
  webapp:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./logs.txt:/opt/logs.txt
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo
  mongo:
    image: mongo